sudo: required
services:
  - docker

before_install:
  - docker build -t raghib1992/react-dev -f Dockerfile.dev .

script:
  - docker run -e CI=true raghib1992/react-dev npm run test

deploy:
  provider: "elasticbeanstalk"
  region: "ap-south-1"
  app: "docker"
  env: "Docker-env"
  bucket-name: "elasticbeanstalk-ap-south-1-561243041928"
  bucket-path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY